### ISSUE TITLE
Simulating MPRA data using estimated distributions from observed data with differnt number tags variant/oligo

### ISSUE THREAD

**Issue by visze** [redaq/atMPRA#1]
Hi,

I want to simulate MPRA data using an estimated distributio from our MPRA experiment. So I would like to generate the `datt` matrix for the `estimateMPRA` function. But every variant (or to be precice every oligo) contains differerent number of barcodes (I guess you call them tags), because barcodes where randomly added after oligo synthesis. Therefore generating `datt` with `nsim*ntag*2` rows is not possible. I can use `nsim*max(ntag)*2` and fill the missing tags with zero but I am wondering if this will work. Do you have any suggestions? Thans a lot.

Best,
Max

**Comment by redaq** [comment]
Hi Max,

This package supports MPRA experiments with a fixed number of barcodes designed for each oligo. In the estimateMPRA function, we assume that we have all the barcodes that should be in the plasmid library. Missing counts for a tag would be assumed to be due to the random sampling from the pool/PCR. It gives information about the sampling procedure. They would be used to estimate the proportion of counts across the barcodes in the plasmid pool. Thus, filing the missing barcodes with zero just to have the nsim*ntag*2 dataframe would be problematic. However, if you know approximately which barcodes are in the plasmid pool (for example, only including those with some counts in at least one DNA or RNA replicate), you can still use this function since it doesn't use the nsim and ntag parameters in the code. It's just trying to estimate the distribution of proportions of counts across barcodes in the library, and the distribution of counts across replicates (RNA or DNA) for each barcode. But later on, when you simulate MPRA data, you still need to provide nsim and ntag.

Hope this helps.

Best,
Dandi

**Comment by visze** [comment]
Hi Dandi,

thank you for your answer. I think I can estimate the complexity and the barcodes in the library (e.g. we sequenced them to make an assignment - BC to oligo). But this will not help because I will not able to simulate the MPRA data with your tool. What a pity. But thank you very much for your answer.

Best,
Max
